#!/bin/bash
# # This script can be scheduled to run daily (or whatever) and validate all defined mods.
#   Then it will verify if the downloaded mods (after validation) contain updates and it will update if needed.
# # It will install/update all defined mods automatically.
# # If a mod updates it will output the result in console and also will put an entry into logs/IMPORTANT_NOTICE.txt
#   so you know if you want to restart your server(s).
# # In case you want to use it for different sets of mods or server clusters, just rename the modscript folder and setup
#   a different mods.conf with the other server paths and mod IDs. Make sure to set a good time apart in schedule because
#   steamcmd won't let it run a new process while the previous one still running.
# # Requires both moddownloader and modunpacker scripts to work.
# # Errors are logged unders logs dir.
# # You can either run with arguments: ./modchecker appid modid1 modid2 modid3 (etc...) or by setting up mods.conf.

# ---------- NO NEED TO EDIT BELOW -----------

# Getting the variables from modfunctions
scriptname="Mod Checker"
if [ ! -z "$*" ]; then
 appid=$(echo "$*" | tr -d '[:alpha:]' | awk '{print $1}')
 modid=( $(echo "$*" | sed "s/$appid //g" | tr -d '[:alpha:]') )
 . $(dirname "$0")/modfunctions "$scriptname" "$appid" "${modid[@]}"
else
 . $(dirname "$0")/modfunctions "$scriptname"
fi

msg="Up and running..." && output_msg

# Downloading/validating the mods
count=1
for i in "${modid[@]}"; do
 msg="Downloading/validating Mod ID: $i" && output_msg
 "${scriptpath}/moddownloader" "$scriptname" "$appid" "$i"
 online=$(cut -d "!" -f 2 "${steaminstallation}/SteamApps/workshop/content/${appid}/${i}/modmeta.info" 2>/dev/null | tr -dc '[:alnum:]')
 eval online${count}="$online"
 eval modid${count}="$i"
 let count=count+1
done

totalmodids=$count

# Comparing the downloaded mods with the installed and updating if needed
count=1
while [ $count -lt $totalmodids ]; do
eval online=\$"online${count}"
eval modid=\$"modid${count}"
 for s in "${server[@]}"; do
  installed=$(cut -d "!" -f 2 "${s}/ShooterGame/Content/Mods/${modid}/modmeta.info" 2>/dev/null | tr -dc '[:alnum:]')
  if [ ! -z "$online" ]; then
   [ -z "$installed" ] && operation="new" || operation="updated"
   if [ -z "$installed" ] || [ "$online" != "$installed" ]; then
    echo
    msg="Installing $operation Mod ID: ${modid}..." && output_msg
    "${scriptpath}/modunpacker" "$scriptname" "$appid" "$modid"
     [ "operation" = "updated" ] && \
     msg="NOTICE: Updated Mod ID: $modid in server: $s \nYou might want to restart your server now!" && msg_output
   fi
  fi
 done
 let count=count+1
done

echo
msg="All Mod IDs and server(s) checked!" && output_msg
