#!/bin/bash
# # This script downloads mods from Steam's workshop with steamcmd.
# # You can either run with arguments: ./moddownloader appid modid1 modid2 modid3 (etc...) or by setting up mods.conf.
# # Requires steamcmd installed.
# # Will resume if download is interrupted until it succeeds (max limit 30 attempts).

# If mods.conf doesn't exist, set below the correct paths
# Will be overriden if you setup the mods.conf
# Add or remove entries following the same pattern
steamcmd="${HOME}"
steaminstallation="${HOME}/.steam"


# ---------- NO NEED TO EDIT BELOW -----------

# Getting the variables from modfunctions
scriptname="Mod Downloader"
if [ ! -z "$*" ]; then
  appid="$1"
  modid=( $(echo "$*" | sed "s/$appid //g") )
 . $(dirname "$0")/modfunctions "$scriptname" "$appid" "${modid[@]}"
else
 . $(dirname "$0")/modfunctions "$scriptname"
fi

# Downloading/validating the mods
function get_mod {
 "${steamcmd}/steamcmd" +login anonymous +workshop_download_item $appid $i validate +exit
}

#msg="Results for App id: $appid" && output_msg

for i in "${modid[@]}"; do
 #for c in {10..01}; do
 # printf "\r\033[K[Mod Downloader] Will start downloading Mod ID: $i for App ID: ${appid} in $c seconds... (Press ctrl+c to cancel)"
 # sleep 1
 #done
 #echo
 msg="Starting downloading/validating Mod ID: $i for App ID: ${appid}..." && output_msg
 count=0
 while true; do
  false
  get_mod
  [ "$?" -eq 0 ] && break
  [ "$count" -ge 30 ] && msg="ERROR: Download attempts of $i reached the maximum limit of 30. Aborting." && output_msg && break
  [ "$?" -ne 0 ] && \
   msg="Something went wrong downloading the Mod ID: $i. Trying again... (Press ctrl+c to cancel) \n Some mods require multiple attempts. Ignore any timeout errors." && \
   output_msg
  let count=count+1
  sleep 2
 done
 echo
 [ ! -d "${steaminstallation}/SteamApps/workshop/content/${appid}/${i}" ] && msg="ERROR: Mod ID: $i for App ID: ${appid} downloaded failed!" || \
  msg="Mod ID: $i for App ID: $appid found successfully downloaded." && output_msg
done
