#!/bin/bash
# # This script downloads mods from Steam's workshop with steamcmd.
# # You can either run with arguments: ./moddownloader appid modid1,modid2,modid3 (etc...) or by setting up mods.conf.
# # Requires steamcmd installed.
# # Will resume if download is interrupted until it succeeds (max limit 30 attempts).

# If mods.conf doesn't exist, set below the correct paths
# Will be overriden if you setup the mods.conf
#Example: steamcmd="${HOME}"
steamcmd=""
#Example: steaminstallation="${HOME}/.steam"
steaminstallation=""

# ---------- NO NEED TO EDIT BELOW -----------

# Getting the variables from modfunctions if needed
scriptname="Mod Downloader"
if [ ! -z "$*" ]; then
 if ! grep ^Mod <<<"$*" &>/dev/null; then
  [ -z "$steamcmd" ] && echo -e "ERROR: steamcmd variable cannot be empty when script is used independently with arguments!\
  \nOpen $scriptname and set the correct paths at the top of the script. Exiting." && exit 1
  [ -z "$steaminstallation" ] && echo -e "ERROR: steaminstallation variable cannot be empty when script is used independently with arguments!\
  \nOpen $scriptname and set the correct paths at the top of the script. Exiting." && exit 1
 fi
 appid=$(echo "$*" | tr -d '[:alpha:]' | awk '{print $1}')
 modid=( $(echo "$*" | sed "s/$appid //g") )
 . $(dirname "$0")/modfunctions "$scriptname" "$appid" "${modid[@]}"
elif [ -z "$*" ]; then
 . $(dirname "$0")/modfunctions "$scriptname"
fi

# Downloading/validating the mods
function get_mod {
 "${steamcmd}/steamcmd" +login anonymous +workshop_download_item "$appid" "$i" validate +exit
}

for i in "${modid[@]}"; do
 # Uncomment the lines below for 10 seconds delay of mods installation to give you time to cancel.
 #for c in {10..01}; do
 # printf "\r\033[K[Mod Downloader] Will start downloading Mod ID: $i for App ID: ${appid} in $c seconds... (Press ctrl+c to cancel)"
 # sleep 1
 #done
 #echo
 echo
 msg="Checking Mod: $modname" && output_msg
 msg="Starting downloading/validating Mod ID: $i for App ID: ${appid}..." && output_msg
 count=0
 while true; do
  false
  get_mod &>/dev/null
  [ "$?" -eq 0 ] && break
  [ "$count" -ge 30 ] && msg="ERROR: Download attempts of $i reached the maximum limit of 30. Aborting." && output_msg && break
  [ "$?" -ne 0 ] && \
   msg="Something went wrong downloading the Mod ID: $i. Trying again... (Press ctrl+c to cancel)" && output_msg
   msg="Some mods require multiple attempts. Ignore any timeout errors." && output_msg
  let count=count+1
  sleep 2
 done
 [ ! -d "${steaminstallation}/SteamApps/workshop/content/${appid}/${i}" ] && msg="ERROR: Failed to download Mod ID: $i for App ID: ${appid}!" || \
  msg="Mod downloaded succesfully." && output_msg
done
